NotJoeMartinez/yt-fts

- README.md
- yt_fts.py
multi threaded downloading. branch from pr #4
> Multithreading vtt downloading 

- yt_fts/yt_fts.py
added check on `parse_vtt` to prevent duplicate text entries when they are only like a 10th of a second appart. It only checks the previous element appended to the `result` array so it shouldn't cut out unnecissary text. Unless someone is just repeating the same word repetativly for like 30 seconds.
> Fixed duplicate subtitle entries in db

- setup.py
- yt_fts/download_scripts.py
- yt_fts/utils.py
- yt_fts/yt_fts.py
- The previous module was getting confusing so I split it up into three files. Technically four but `db_scripts.py` is already separate. 
- `yt_fts.py` is still the "entry point" for the click cli, but now most of the messy functions are abstracted away 
- `download_scripts.py` handles all the downloading and session management 
-  `utils.py` Is where I'm putting all the functions that don't belong anywhere else
- Added some doc strings
> Split functions into four modules 

- setup.py
- yt_fts/yt_fts.py
> added version flag

- .gitignore
- tests/TESTING.md
- tests/basic.sh
Added cli test script, there are way better ways to do this but this is the start.
> added testing script

- README.md
- setup.py
- yt_fts/yt_fts.py
Added more details in click help commands and used the same text in the help commands in the docs.
> Update docs syntax

- requirements.txt
- yt_fts/semantic_serch/open_ai_auth.py
- yt_fts/yt_fts.py
Added basic authentication through environment or optional commandline argument with the `generate_embedings` command.
> Open ai auth

- requirements.txt
- yt_fts/db_utils.py
- yt_fts/semantic_serch/embeddings.py
- yt_fts/semantic_serch/open_ai_auth.py
- yt_fts/yt_fts.py
For " Integrate semantic search with OpenAI embedings API #21" 
- Added functions for getting embeddings from openAI API and saved them to `embeddings.db`
> Get embeddings

- setup.py
- yt_fts/list_utils.py
- yt_fts/utils.py
- yt_fts/yt_fts.py
slow imports seems to be caused by openai imports 
copped `check_ss_enabled` function to `list_utils`  until I can figure out how to prevent this issue
> fixed slow imports (hotfix) 0.1.17

- setup.py
- yt_fts/yt_fts.py
changed
```python
if check_ss_enabled(channel_id) != None:
```
to 
```python
if check_ss_enabled(channel_id) == True:
```
> fixed bug with generate embeddings (0.1.19) 

- README.md
- yt_fts/db_utils.py
- yt_fts/yt_fts.py
- Delete now deletes embeddings tables
- Delete now requires `--channel` flag
> Enable delete for semantic

- README.md
- setup.py
- yt_fts/show.py
- yt_fts/utils.py
- yt_fts/yt_fts.py
- Show command allows listing of existing videos in channel with `show --channel <channel_id>
- Show command can display transcript of a video with`show --video <video_id>`
> Add show command

- README.md
- setup.py
- yt_fts/export.py
- yt_fts/yt_fts.py
- Turned `export` into a flag passed to search
> Make export a flag

- README.md
- setup.py
- yt_fts/yt_fts.py
- added short hand flags to rest of commands
- renamed `generate-embeddings` to `get-embeddings`
> added short flags, changed generate embeddings

- yt_fts/search.py
- wasn't calling  `save_search_embedding(text, search_embedding)`
> fixed probelm with search hist not saving

- yt_fts/search.py
Summary now shows at bottom of search.
> Show summary on search

- .gitignore
- requirements.txt
- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/embeddings.py
- yt_fts/list.py
- yt_fts/yt_fts.py
From #73 
- Replaced all usage of [tabulate](https://github.com/astanin/python-tabulate) and [progress](https://github.com/verigak/progress) with [rich](https://github.com/Textualize/rich)
- Rich and progress from requirments.txt 
- Refactored brain dead download command, need to make an issue for this one
> Move to rich

- README.md
- yt_fts/yt_fts.py
`yt-fts config` now shows config directory
> added config command

- yt_fts/db_utils.py
- yt_fts/update.py
- yt_fts/vector_search.py
`delete_channel` now checks if semantic search is enabled and deletes documents from collection where
channel_id = deleted channel
> Chroma integration delete vector store

- yt_fts/db_utils.py
- yt_fts/embeddings.py
- Removed Embeddings and SemanticSearchHist tables
- Removed delete Embeddings statment from delete command
> removed Embeddings table

- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/embeddings.py
- yt_fts/export.py
- yt_fts/list.py
- yt_fts/search.py
- yt_fts/utils.py
- yt_fts/vector_search.py
This probably broke something, which is why I need to start working on testing
> added end_time, changed timestamp to start_time everywhere

- tests/test_export.py
- tests/test_vector_search.py
- yt_fts/export.py
Getting this to be effective might require adding asynchronous functionality to the download functions.  
run with `python -m unittest tests/test_export.py`
> Added basic unit tests with unittest module

- .gitignore
- CHANGELOG.md
- README.md
- requirements.txt
- tests/test_export_transcripts.py
- tests/test_split_subtitles.py
- tests/view_chromadb.py
- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/embeddings.py
- yt_fts/export.py
- yt_fts/utils.py
- yt_fts/vector_search.py
- yt_fts/yt_fts.py
> Increase context window

- yt_fts/db_utils.py
- yt_fts/search.py
- yt_fts/yt_fts.py
Added `--limit` option to fts search
> added limit option to fts search

- yt_fts/search.py
- yt_fts/vector_search.py
- yt_fts/yt_fts.py
- added summary to vector search 
- refactored summary on fts search to not use unnecessary function
- Made it say "1 channel" when only one channel searched
> added summary string to vector search

- .gitignore
- yt_fts/export.py
- yt_fts/yt_fts.py
`yt-fts export -c 1` writes a directory with the name of the channel id in channel slot 1 and writes 
text files for every video id in the channel.
> added export option

- .gitignore
- yt_fts/download.py
- yt_fts/export.py
- yt_fts/yt_fts.py
- `export -c 1 -f vtt` will now export to `{channel_id}_vtt` 
- removed print statement from `get_channel_id_from_input`
> added vtt export options

- yt_fts/search.py
- yt_fts/utils.py
- yt_fts/vector_search.py
- yt_fts/yt_fts.py
> search and vsearch now highlight matched words

- yt_fts/search.py
- yt_fts/yt_fts.py
- Added more detailed help with advanced query syntax when the initial query fails
> added advanced query syntax help

- pyproject.toml
- requirements.txt
- yt_fts/config.py
- yt_fts/embeddings.py
- yt_fts/vector_search.py
- disabled spooky chromadb telemetry
- see: disable chromadb opentelemetry #130 
- updated dependencies for rich, bs4 & openAI
> Disable chromadb opentelemetry, updated dependencies

- tests/test_playlist_urls.py
- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/update.py
- yt_fts/yt_fts.py
> [Feature request] Playlist support #18 
Playlists downloading now available with `--playlist/-p`
```
yt-fts download -j 5 -p "playlist url"
```
> Playlist support

- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/export.py
- yt_fts/search.py
- yt_fts/utils.py
Allowing things like sorting a CSV export by date.
Database schema is backwards incompatible and requires manual migration.
> also store and export video (upload) date

- yt_fts/config.py
- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/embeddings.py
- yt_fts/export.py
- yt_fts/list.py
- yt_fts/search.py
- yt_fts/update.py
- yt_fts/utils.py
- yt_fts/vector_search.py
- yt_fts/yt_fts.py
Used pycharm linter to handle most pep 8 problems, all tests passed... i think
> Pep 8 style

- yt_fts/search.py
- yt_fts/yt_fts.py
Removed all `import *` statements and used explicit imports
> Fix import all

- yt_fts/llm.py
- yt_fts/yt_fts.py
> changed model to 4o

- yt_fts/download.py
- yt_fts/get_embeddings.py
- yt_fts/llm.py
- yt_fts/utils.py
- yt_fts/vector_search.py
- yt_fts/yt_fts.py
- Refactored get_embeddings to be an object
- Added metadata context for embeddings
- chroma ids are now uuids
> Add metadata to embeddings

- README.md
- pyproject.toml
- requirements.txt
- yt_fts/db_utils.py
- yt_fts/download.py
- yt_fts/get_embeddings.py
- yt_fts/llm.py
- yt_fts/utils.py
- yt_fts/yt_fts.py
- Fixed `parse_vtt` not parsing standard vtt files using webvtt
- Fixed full text search breaking when quotes are in search query
- Changed default interval to 30 seconds 
- Log error when interval is longer than video
> Fix vtt parsing failing

- yt_fts/db_utils.py
- yt_fts/search.py
Issue: https://github.com/NotJoeMartinez/yt-fts/issues/164
- Fixed `OR` and `AND` operators
- Moved sql query method off of `sqlite-utils`
- Updated formatting of error messages
> Fix or and search

- yt_fts/get_embeddings.py
- yt_fts/search.py
- yt_fts/yt_fts.py
- Full Text Search mode is now handled by  the `SearchHandler` class
- The Flag `--video` `-v` for search is now `--video-id`
> Full Text Search OOP refactor

- README.md
- tests/test_download.py
- tests/test_search.py
- yt_fts/export.py
- yt_fts/search.py
- yt_fts/yt_fts.py
- `export` command now uses `ExportHandler`  class
- Updated test passing threshold to accommodate for new rate limiting
- Updated docs to show usage of `--cookies-from-browser`
- Status updates to export command
> Export oop refactor

- yt_fts/db_utils.py
- yt_fts/search.py
- yt_fts/summarize.py
- yt_fts/yt_fts.py
- `summarize` command https://github.com/NotJoeMartinez/yt-fts/issues/169
- `search` now displays the video id
> Add summarize command

- yt_fts/download.py
This fixes #184 and should make channel title extraction more robust in the future.
> Take channel name from RSS feed

- README.md
- pyproject.toml
- src/yt_fts/config.py
- src/yt_fts/llm/chatbot.py
- src/yt_fts/llm/get_embeddings.py
- src/yt_fts/llm/summarize.py
- src/yt_fts/search.py
- src/yt_fts/utils.py
- src/yt_fts/yt_fts.py
- tests/test_download.py
- tests/test_search.py
- tests/testing_utils.py
- tests/view_chromadb.py
I tried to keep the changes as small as possible
- Added support for Gemini
- Used batch embedding to avoid hitting the rate limits on Gemini and reduce embedding time
- Updated README to reflect the changes
- Fixed some minor issues in the tests
- The limit of 10 results was too low
- `rich.Console` sets console width to 80 if `COLUMNS` env variable is not set and adds newlines to console output
- The test database doesn't work with 768 dimensional embeddings cause its uses 1536
- Cut embedding time by half went from `58.73s` to `26.27s` for a channel with 20 videos
- All tests are passing with my own database
```YT_FTS_TEST_RESET=false pytest tests/```
> Add support for free Gemini embedding and chat models 
