README.md
yt_fts.py

Allow the user to specify a subtitles language (defaut to english).

Specify subtitles language

---

yt_fts.py

Fixes #1
Mock a "Reject all" click on YouTube cookies consent page.

Handle reject consent cookie

---

yt_fts.py

`json.loads()` breaks on line 210 when trying to read script tag string with a channel that has special characters in it's 
name #8. I added a try except statement to `get_channel_name` function so it attempts to parse the json of the script tag normally, then escapes all escape characters if it fails. I want to preserve these special character codes for later use in displaying the channel name and don't know what the effect of replacing all escape sequences by default will be.

hot fix for special chars in channel name

---

README.md
setup.py
yt_fts/db_scripts.py
yt_fts/yt_fts.py

- Added multi channel search and export functionality via `--all` flag 
- This mixes channels together so I added [`get_channel_name_from_video_id`](https://github.com/NotJoeMartinez/yt-fts/blob/57db41222643f7c07b4347f9dee08e0244d5ae4c/yt_fts/db_scripts.py#L113) to get channel name from a video id 
- Channel names now output to console and csv to prevent confusion when running multi channel search 
Search query now goes before ids or flags. The intent is to cut down on users having to retype search queries because they forgot to copy the id. 
```bash
yt-fts search "text to search" [channel_id]
yt-fts search "text to search" --all 
```
**Ex:**
```bash
yt-fts search "in the big city" UC4woSp8ITBoYDmjkukhEhxg 
yt-fts search "in the big city" --all
```

Seach all channels

---

README.md
setup.py
yt_fts/db_scripts.py
yt_fts/utils.py
yt_fts/yt_fts.py

- search, export and delete commands can now be specified with channel name or row ID
- `yt-fts search [SEARCH_TEXT] [NAME_OF_CHANNEL or ID]`
- Introduces bug with RowID and numerical channel name confusion  
On issue #3 it was suggested to allow channel aliasing to prevent users from having to input the whole `channel_id`. This pr somewhat implements this except the alias are already defined by SQLite Row IDs. This has the slight drawback that the ids will stop being numerical if a user deletes a channel but it's way better than having to manually copy and paste the channel id. I added the ability to search by channel name and some error checking for if they have two channels named the same. I implemented this for the commands `export` and `delete` as well.
**This technically introduces …

Allow for searching by channel name and Rowid

---

.gitignore
README.md
setup.py
tests/basic.sh
yt_fts/db_utils.py
yt_fts/download_utils.py
yt_fts/search_utils.py
yt_fts/yt_fts.py

Users can now use `--video` to search for keywords within a video. The argument provided must be the
video id of the YouTube video.
syntax: 
```bash
yt-fts search "SEARCH_TEXT" --video [VIDEO_ID]
```
modified search syntax to be more explicate about the scope of the search. User must use channel, all or video flags
to specify which scope they intend to search in. 
old:
```bash
yt-fts search "life in the big city" "The Tim Dillon Show"
yt-fts search "life in the big city" 1
```
new
```bash
yt-fts search "life in the big city" --channel "The Tim Dillon Show"
yt-fts search "life in the big city" --channel 1
```
This will make it easier for users that want to use the video id in their next search
**Ex:**
```bash
yt-fts search "rea* kni* Mali*" --channel "The Tim Dillon Show" 
```
output:
``` …
```

Search individual videos

---

.gitignore
README.md
setup.py
yt_fts/config.py
yt_fts/db_utils.py
yt_fts/download_utils.py
yt_fts/list_utils.py
yt_fts/semantic_serch/embeddings.py
yt_fts/semantic_serch/search_embeddings.py
yt_fts/show.py
yt_fts/yt_fts.py

-Subtitles database now saved to platform specific config directory 
- macos and linux: `~/.config/yt-fts`
- windows `APPDATA\yt-fts`
-Replaced hard coded db paths with `get_db_path()` function. 
- If it fails to find a database in the config path it just returns "subtitles.db.
-Tested on macos and a couple linux distros. still need to test on windows. 
- Lowered required python version to `3.8` 
- Added `--conifg` to the show command to show the user where their database is located

Make config directory

---

yt_fts/download.py
yt_fts/yt_fts.py

from #67 
- `validate_channel_url`  now fixes incorrect channel urls by adding on or replacing `/videos` 
- It will now take both channel id urls and the newer ampersand channel name urls
- Used rich to print the eorrors

made validate_channel_url more flexible

---

.gitignore
yt_fts/config.py
yt_fts/yt_fts.py

The subtitle database was always being set to current directory. I'm not sure when this was introduced.
- `get_db_path()` now creates a configuration directory by default and will still make a subtitles db in current directory if something fails
- the `config` command now prints full database path
- removed whatever was happening in `cli`, was originally supposed to be a bootstrapping thing but it doesn't work and was a bad idea to begin with.

Fixed bootstrapping config dir and directory

---

tests/view_chromadb.py
yt_fts/db_utils.py
yt_fts/vector_search.py

Issue was with removing the `channel_id` from the `SemanticSearchEnabled` table before checking to see if the channel needed to be deleted from chroma.

Fixed Chromadb not deleting documents 

---

yt_fts/download.py

Downloading streams is the same process as downloading videos. 
The problem was that our function to get all of a channels videos doesn't
get all videos under `/streams` so I just added another sub process call to 
yt-dlp using the same flags but with `/streams` instead of `/videos`

Support Live Streamed Videos

---

yt_fts/download.py

Hello!
I've been working with your tool and ran into an issue that I wanted to address. Though this is a tiny contribution, so I'm excited to propose this fix!
**Issue Encountered:**
While fetching video ids using `yt-dlp` for channels without a streams tab (as in my sample channel here), the script crashes with the following error:
```
subprocess.CalledProcessError: Command '['yt-dlp', '--flat-playlist', '--print', 'id', 'https://www.youtube.com/channel/UCwpMRCoVgSJ-rKyV1yhWljg/streams']' returned non-zero exit status 1.
```
And `yt-dlp` outputs:
```
ERROR: [youtube:tab] UCwpMRCoVgSJ-rKyV1yhWljg: This channel does not have a streams tab
```
**Proposed Solution:**
I've added a try-except block to the `get_videos_list`  function in `download.py` to handle this gracefully. The script now …

Implement Error Handling for Missing Streams Tab in yt-dlp Calls

---

.gitignore
tests/test_parse_vtt.py
yt_fts/utils.py
yt_fts/yt_fts.py

instead of skipping iteration when encountering a duplicate simply replace
the previous entry with the current entry
```python
if result and result[-1]['text'] == sub_titles.strip('\n'):
result[-1] = {
'start_time': start_time,
'stop_time': stop_time,
'text': sub_titles.strip('\n'),
}           
```

fixed issue with incorrect end time

---

yt_fts/db_utils.py

The delete function checks calls `check_ss_enabled` after opening 
an sqlite connection, `check_ss_enabled` also opens a connection. 
```python
conn = sqlite3.connect(get_db_path())
cur = conn.cursor()
...
if check_ss_enabled(channel_id):
delete_channel_from_chroma(channel_id)
```
Concurrent reading should be okay with sqlite and this was fine when
I was testing it, but now I'm getting database lock errors. Quick fix is just 
to move the call to `check_ss_enabled` to before opening the other connection

Db lock error on delete

---

yt_fts/yt_fts.py

Muscle memory demands `-h` :sweat_smile: 
Would you consider an additional commit enabling `no_args_is_help` from https://click.palletsprojects.com/en/8.1.x/api/#click.Command?

Allow specifying -h for help

---

yt_fts/download.py

Fixes #123
I've only tested this on a couple of different examples but it seems to work fine and improve performance of the final step of download quite a bit.

Download video metadata at subtitle download time

---

Makefile
yt_fts/search.py
yt_fts/utils.py

Made fts search easier to look at

Make terminal colors less ugly

---

yt_fts/download.py

Original issue was with `get_vid_title()` function but it was removed in 58b538b so we could just read the JSON from the calling function. I have not been able to reproduce this, could be isolated to windows systems. Either way specifying UTF-8 encoding shouldn't break anything.

Hotfix for unicode decode error #138 

---

pyproject.toml
requirements.txt
yt_fts/download.py
yt_fts/yt_fts.py

No longer using subprocess #146

using yt-dlp package instead of subprocess

---

tests/TESTING.md
yt_fts/db_utils.py
yt_fts/download.py
yt_fts/export.py
yt_fts/search.py
yt_fts/utils.py
yt_fts/vector_search.py
yt_fts/yt_fts.py

- Tried refactor the download.py module into OOP 
- Realized that this could break too many unknown things unless we have unit good testing 
- moved `handle_reject_consent_cookie` to `utils`
- moved `get_channel_id_from_input` to `db_utils`
- added more details to testing document

Attempted refactor to download class

---

tests/test_download.py
tests/test_export.py
tests/test_search.py
tests/test_vsearch.py
yt_fts/db_utils.py
yt_fts/download.py
yt_fts/search.py
yt_fts/update.py
yt_fts/yt_fts.py

Added exit codes where possible so that we can test against it. 
Did some PEP 8 style changes.

Exit with sys

---

tests/test_download.py
yt_fts/llm.py
yt_fts/yt_fts.py

Added `llm` command that does 
llm stuff on the dataset

Llm rag integration

---

pyproject.toml
tests/test_download.py
yt_fts/download.py
yt_fts/yt_fts.py

This pull request introduces changes to improve the functionality and usability of the YouTube channel downloader. Key updates include modifying the behavior for handling duplicate channels, increasing the default number of parallel jobs, fixing a typo in a variable name, and adding a new test case for channel updates. These changes enhance user experience and improve code reliability.
* [`yt_fts/download.py`](diffhunk://#diff-e33c32d6d9355bccfa49d5b2317425da129b78039e78d52811f43726836fcfbbL55-R57): Updated the `download_channel` method to allow updating existing channels instead of exiting with an error. Removed the `handle_channel_exists` method, which previously handled duplicates by displaying an error message. [[1]](diffhunk://#diff-e33c32d6d9355bccfa49d5b2317425da129b78039e78d52811f4 …

Fix download format errors, bump yt-dlp version, set default jobs to 8
